global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:5001"]

  - job_name: item-service
    metrics_path: /metrics
    static_configs:
      - targets: ["item-service:5002"]

  - job_name: rental-service
    metrics_path: /metrics
    static_configs:
      - targets: ["rental-service:5003"]

  - job_name: review-service
    metrics_path: /metrics
    static_configs:
      - targets: ["review-service:5004"]

  - job_name: chat-service
    metrics_path: /metrics
    static_configs:
      - targets: ["chat-service:5005"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
